---
title: "Fitting Stan"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(cmdstanr)
library(posterior)
library(bayesplot)
library(shinystan)
library(dplyr)
library(ggplot2)
```

```{r}
options(mc.cores=parallel::detectCores())
check_cmdstan_toolchain(fix = TRUE)
set_cmdstan_path("C:\\Users\\daniel.park\\.cmdstanr\\cmdstan-2.28.0")
```

```{r}
library(nleqslv)

equilibrium_f <- function(x, parms) {
  A_t <- parms[1]
  B_t <- parms[2]
  C_t <- parms[3]
  K_AB <- parms[4]
  K_BC <- parms[5]
  alpha <- parms[6]

  A <- exp(x[1])
  C <- exp(x[2])
  ABC <- exp(x[3])

  F1 <- A + K_BC * ABC / (alpha * C) + ABC - A_t
  F2 <- K_AB * K_BC * ABC / (alpha * A * C) + K_BC * ABC / (alpha * C) + K_AB * ABC / (alpha * A) + ABC - B_t
  F3 <- C + K_AB * ABC / (alpha * A) + ABC - C_t
  return(c(F1 = F1, F2 = F2, F3 = F3))
}

equilibrium_jac <- function(x, parms) {
  K_AB <- parms[4]
  K_BC <- parms[5]
  alpha <- parms[6]

  A <- exp(x[1])
  C <- exp(x[2])
  ABC <- exp(x[3])

  df_dy <- rbind(
    c(A, -K_BC * ABC / (alpha * C), K_BC * ABC / (alpha * C) + ABC),
    c(
      -K_AB * K_BC * ABC / (alpha * A * C) - K_AB * ABC / (alpha * A),
      -K_AB * K_BC * ABC / (alpha * A * C) - K_BC * ABC / (alpha * C),
      K_AB * K_BC * ABC / (alpha * A * C) + K_BC * ABC / (alpha * C) + K_AB * ABC / (alpha * A) + ABC
    ),
    c(-K_AB * ABC / (alpha * A), C, K_AB * ABC / (alpha * A) + ABC)
  )
  return(df_dy)
}

noncoop_f <- function(parms) {
  A_t <- parms[1]
  B_t <- parms[2]
  C_t <- parms[3]
  K_AB <- parms[4]
  K_BC <- parms[5]

  A <- A_t - ( A_t + B_t + K_AB - sqrt( (A_t + B_t + K_AB)**2 - 4 * A_t * B_t ) ) / 2
  C <- C_t - ( C_t + B_t + K_BC - sqrt( (C_t + B_t + K_BC)**2 - 4 * C_t * B_t ) ) / 2
  
  A <- ifelse(A <= 0, 1e-19, A)
  C <- ifelse(C <= 0, 1e-19, C)

  phi_AB <- A_t - A
  phi_BC <- C_t - C
  ABC <- ifelse(B_t == 0, 1e-19, phi_AB * phi_BC / B_t)
  return(c(A, C, ABC))
}

wrap_solve <- function(parms) {
  noncoop_sols <- noncoop_f(head(parms, -1))
  init_guess <- log(noncoop_sols)
  equilibrium_roots <- nleqslv(
    x = init_guess,
    fn = equilibrium_f,
    jac = equilibrium_jac,
    parms = parms
  )
  return(exp(equilibrium_roots$x[3]))
}

```

# NANOBRET data processing
```{r}
nanobret_csv <- read.csv("data/corrected_nanobret_df.csv")

sorted_min <- sort(unique(nanobret_csv$Minutes))

# subtract min mBU within Construct group
nanobret_96 <- nanobret_csv %>% 
  filter(Minutes %in% sorted_min[6:7]) %>%
  group_by(Construct) %>%
  mutate(mBU_corrected = (mBU_corrected - min(mBU_corrected)) )

ggplot(nanobret_96, aes(x = uM, y = mBU_corrected, color = Construct)) +
  geom_point() +
  geom_line() +
  scale_x_log10()

nanobret_96 <- nanobret_96 %>% mutate(construct_int = recode(Construct,
  "VHL_WT SMARCA2_L1415S" = 1,
  "VHL_WT SMARCA2_E1420S" = 2,
  "VHL_R69Q SMARCA2_WT" = 3,
  "VHL_Y112F SMARCA2_WT" = 4,
  "VHL_WT SMARCA2_WT" = 5
))

ggplot(nanobret_96, aes(x = uM, y = mBU_corrected, color = as.factor(construct_int))) +
  geom_point() +
  geom_line() +
  scale_x_log10() +
  guides(color = guide_legend(title = bquote(alpha[i])))

nanobret_96

```

```{r}
uM_unique <- unique(nanobret_96$uM)

A_t <- 5e-8
C_t <- 1e-2
K_AB <- 5e-5
K_BC <- 1e-6
alpha <- 1

wrap_solve(c(A_t, 5000, C_t, K_AB, K_BC, alpha))
noncoop_f(c(A_t, 5000, C_t, K_AB, K_BC))
```

# CMDSTAN

```{r}
register_knitr_engine(override = FALSE)
```

```{cmdstan, output.var="eq_model"}
functions {
  vector noncoop_sols(vector parms) {
    vector[3] sols;  // solutions [A], [C], [ABC] to non-cooperative equilibrium system
    real A;
    real C;
    real ABC;
    
    real phi_AB;
    real phi_BC;

    real A_t = parms[1];
    real B_t = parms[2];
    real C_t = parms[3];
    real K_AB = parms[4];
    real K_BC = parms[5];
  
    A = A_t - ((A_t + B_t + K_AB - sqrt(square(A_t + B_t + K_AB) - 4 * A_t * B_t)) / 2);
    C = C_t - ((C_t + B_t + K_BC - sqrt(square(C_t + B_t + K_BC) - 4 * C_t * B_t)) / 2);
  
    if (A < 0) { 
      A = 1e-19; 
    }
    if (C < 0) { 
      C = 1e-19; 
    }
    
    phi_AB = A_t - A;
    phi_BC = C_t - C;
    if (B_t == 0) {
      ABC = 0;  // verify that root-finding transformation handles 0
    } else {
      ABC = phi_AB * phi_BC / B_t;
    }
    
    sols[1] = A;
    sols[2] = C;
    sols[3] = ABC;
    return sols;
  }
  
  vector system(vector y, vector theta, data real[] x_r, int[] x_i) {
    // y: unknown variables to solve for
    // theta: parameters [A]_t, [B]_t, [C]_t, alpha
    // x_r: data K_AB, K_BC
    // y_trans: f(y) = [A], [C], [ABC]
    // initial guesses y should be close to f-inv([A], [C], [ABC])
    vector[3] z;  // the system of mass-action equations
    vector[3] y_trans;  // transform y to constrain [A], [C], [ABC] >= 0
    real A;
    real C;
    real ABC;

    real A_t = theta[1];
    real B_t = theta[2];
    real C_t = theta[3];
    real alpha = theta[4];
    real K_AB = x_r[1];
    real K_BC = x_r[2];
    
    y_trans = square(y); 
    A = y_trans[1];
    C = y_trans[2];
    ABC = y_trans[3];

    z[1] = A + K_BC * ABC / (alpha * C) + ABC - A_t;
    z[2] = K_AB * K_BC * ABC / (alpha * A * C) + K_BC * ABC / (alpha * C) + K_AB * ABC / (alpha * A) + ABC - B_t;
    z[3] = C + K_AB * ABC / (alpha * A) + ABC - C_t;
    return z;
  }
}

data {
  int<lower=0> N;  // number of data points
  int<lower=1> N_construct;  // number of constructs
  real<lower=0> K_Ds[2];  // [K_AB, K_BC]
  vector<lower=0>[N] B_x;  // extracellular [B]_x
  int<lower=1> construct[N];  // array of integers identifying construct of row i
  vector<lower=0>[N] mBU;  // observed mBU
}

transformed data {
  int x_i[0];  // necessary for algebra_solver() call signature
  real kappa = 0.9;
  real C_t = 0.15;
  real A_t = 0.05;
  real log_beta = 5;
  real alpha[5] = {20, 26, 20, 20, 26};
}

parameters {
  //real<lower=0> C_t;  // total intracellular E3 concentration
  //real<lower=0.2*C_t, upper=0.5*C_t> A_t;  // total intracellular target protein concentration
  //real<lower=0> alpha[N_construct];  // alpha[c] for each construct type c
  //real<lower=0, upper=1> kappa;
  //real log_beta;
  real<lower=0> sigma;  // mBU error 
}

transformed parameters {
  vector[N] predmBU;  // predicted mean mBU
  
  print(C_t);
  print(A_t);
  print(alpha);
  
  for (i in 1:N) {
    real B_t = B_x[i] * kappa;

    vector[3] noncoop_solutions = noncoop_sols( [ A_t, B_t, C_t, K_Ds[1], K_Ds[2] ]' );
    vector[3] y_init = sqrt(noncoop_solutions);
    print(alpha[construct[i]]);
    vector[4] theta = [ A_t, B_t, C_t, alpha[construct[i]] ]';  
    vector[3] roots = algebra_solver_newton(system, y_init, theta, K_Ds, x_i);
    vector[3] coop_solutions = square(roots); 

    real predABC = coop_solutions[3];

    predmBU[i] = predABC * exp(log_beta);
  }
  print(predmBU);
}

model {
  //C_t ~ gamma(1, 1);
  //A_t ~ gamma(1, 1);
  //for (c in 1:N_construct) {
    //alpha[c] ~ normal(30, 10); 
  //}
  //kappa ~ uniform(0, 1);
  //log_beta ~ normal(0, 100);
  sigma ~ exponential(10); 
  
  for (i in 1:N) {
    mBU[i] ~ normal(predmBU[i], sigma);
  }
}
```

```{r}
# model data
stan_data <- list(
  N = nrow(nanobret_96),  # number of rows
  N_construct = length(unique(nanobret_96$construct_int)),  # number of constructs
  K_Ds = c(9.26, 0.0694),  # K_Ds in uM
  B_x = nanobret_96$uM,  # extracellular [B]_x in uM
  construct = nanobret_96$construct_int,  # construct index of row i
  mBU = nanobret_96$mBU_corrected  # observed mBU
)

inits_f <- function() {
  C_t <- runif(1, min = 0, max = 5)
  
  list(
    # C_t = C_t,
    # A_t = 0.35*C_t,
    # alpha = rnorm(n = stan_data$N_construct, mean = 30, sd = 5)
    # log_beta = rnorm(n = 1, mean = 0, sd = 1),
    sigma = rexp(n = 1, rate = 10)
  )
}
```

```{r}
eq_model$check_syntax()

eq_model$print()
```

```{r}
eq_fit <- eq_model$sample(data = stan_data, 
                          # seed = 0, 
                          refresh = 10, 
                          init = inits_f, 
                          iter_warmup = 10, 
                          iter_sampling = 10,
                          chains = 1,
                          # adapt_delta = 0.9
                          )
```

```{r}
eq_fit$save_object(file = "fitMCMC_alpha5_Ct2_At0.66.rds")
```

```{r}
eq_fit <- readRDS("CmdStanMCMC/eq_fit_nalpha_2.rds")
```

```{r}
eq_fit$cmdstan_diagnose()

eq_fit$summary()
```

```{r}
mcmc_areas(
  eq_fit$draws(), 
  pars = c("C_t", "A_t"), 
  transformations = log, 
  prob = 0.8
  )

color_scheme_set("mix-blue-pink")
mcmc_trace(
  eq_fit$draws(), 
  pars = c("C_t", "A_t"), 
  facet_args = list(nrow = 3)
)
```


```{r}
mcmc_areas(
  eq_fit$draws(), 
  regex_pars = "alpha*",
  prob = 0.8
  )

mcmc_trace(
  eq_fit$draws(), 
  regex_pars = "alpha*",
  facet_args = list(nrow = 3)
)
```

```{r}
mcmc_areas(
  eq_fit$draws(), 
  regex_pars = "*beta",
  prob = 0.8
  )

mcmc_trace(
  eq_fit$draws(), 
  regex_pars = "*beta",
)
```

## PREDICT

```{r}
A_t <- eq_fit$summary(variables = "A_t")[['mean']]
# A_t <- .2
C_t <- eq_fit$summary(variables = "C_t")[['mean']]
alpha <- eq_fit$summary(variables = c("alpha[1]", "alpha[2]", "alpha[3]", "alpha[4]", "alpha[5]"))[['mean']]
log_beta <- eq_fit$summary(variables = 'log_beta')[['mean']]
B_x <- unique(nanobret_96$uM)

predmBU <- numeric(length(B_x) * stan_data$N_construct)
alpha_c <- numeric(length(predmBU))
for (i in 1:stan_data$N_construct) {
  for (j in 1:length(B_x)) {
    B_t <- B_x[j]
    predmBU[(i-1)*length(B_x) + j] <- wrap_solve(c(A_t, B_t, C_t, stan_data$K_Ds[1], stan_data$K_Ds[2], alpha[i])) * exp(log_beta)
    alpha_c[(i-1)*length(B_x) + j] <- alpha[i]
  }
}

```

```{r}
fitted_df <- data.frame(
  uM = c(nanobret_96$uM, rep(B_x, stan_data$N_construct)),
  mBU = c(nanobret_96$mBU_corrected, predmBU),
  Construct = c(nanobret_96$Construct, alpha_c),
  construct_int = c(nanobret_96$construct_int, rep(NA, length(predmBU)))
)

ggplot(fitted_df, aes(x = uM, y = mBU)) +
  geom_point(data = fitted_df %>% filter(substr(Construct, start = 1, stop = 1) == "V"),
             aes(color = factor(construct_int))) +
  geom_line(data = fitted_df %>% filter(substr(Construct, start = 1, stop = 1) != "V"),
             aes(color = Construct)) +
  scale_x_log10() +
  guides(color = guide_legend(title = expr(alpha[i])))
```

```{r}
C_t <- 5e-8
A_t <- C_t * 0.33

alpha <- 30
log_beta <- 34.2
B_x <- unique(nanobret_96$uM)

predmBU <- numeric( length(B_x) )
for (i in 1:length(B_x)) {
  B_t <- B_x[i] * 0.75
  predmBU[i] <- wrap_solve(c(A_t, B_t, C_t, stan_data$K_Ds[1], stan_data$K_Ds[2], alpha)) * exp(log_beta)
}

plot(B_x, predmBU, type = "p", log = "x", ylim = c(0, 3.5))
points(B_x, nanobret_96 %>% filter(Construct == "VHL_WT SMARCA2_WT") %>% ungroup() %>% pull(mBU_corrected),
       col = "tomato", pch = 19)
lines(B_x, predmBU)
```

## RSTAN

```{r}
# fit stan
fit_nanobret <- stan(file = "equilibrium.stan", 
                     data = stan_data,
                     # init = inits_f,
                     chains = 1,
                     iter = 2000,
                     cores = 1,
                     # control = list(adapt_delta = 0.9),
                     )
```

```{r}
# save stan_fit object
saveRDS(fit_nanobret, "fit_nanobret.rds")
```

```{r}
print(fit_nanobret)
```

```{r}
pairs(fit_nanobret)
plot(fit_nanobret)
traceplot(fit_nanobret)
```



# TEST STAN


```{r}
fit1 <- stan(file = "test_equilibrium.stan", algorithm = "Fixed_param", 
             data = list(N = nrow(nanobret_96),
                         N_construct = length(unique(nanobret_96$construct_int)),
                         K_Ds = c(1.8, .25),
                         B_x = nanobret_96$uM,
                         construct = nanobret_96$construct_int),
             iter = 1, chains = 1)
```

# TESTING RSTAN

```{r}
file <- file.path(cmdstan_path(), "examples", "bernoulli", "bernoulli.stan")
mod <- cmdstan_model(file) 
```
```{r}
mod$print()

# names correspond to the data block in the Stan program
data_list <- list(N = 10, y = c(0,1,0,0,0,0,0,0,0,1))

fit <- mod$sample(
  data = data_list,
  seed = 123,
  chains = 4,
  parallel_chains = 4,
  refresh = 500
)
```

```{r}
fit$summary()

```

